name: Build LaTeX document
on: 
  push:
    tags:
      - "!v*"
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        latex: [xelatex, lualatex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis.tex
          latexmk_use_${{ matrix.latex }}: true
          args: '-bibtex'

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF_${{ matrix.latex }}
          path: njuthesis.pdf
