name: Build LaTeX document
on: 
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          
      - name: Download njuvisual package (1/2)
        uses: wei/curl@master
        with:
          args: -s -o "njuvisual.dtx" "https://mirror.nju.edu.cn/CTAN/macros/latex/contrib/njuvisual/njuvisual.dtx"
      
      - name: Download njuvisual package (2/2)
        uses: wei/curl@master
        with:
          args: -s -o "njuvisual-curves.dtx" "https://mirror.nju.edu.cn/CTAN/macros/latex/contrib/njuvisual/njuvisual-curves.dtx"
 
      - name: Extract cls from njuthesis
        uses: FengChendian/latex-dtx2cls-action@4.0.1
        with:
          root_file: njuthesis.dtx
          working_directory: ./source/
 
      - name: Extract sty from njuvisual
        uses: FengChendian/latex-dtx2cls-action@4.0.1
        with:
          root_file: njuvisual.dtx
          working_directory: ./

      - name: Compile class documentation
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis.dtx
          working_directory: ./source/
          latexmk_use_xelatex: true
          args: "-bibtex"
          pre_compile: "xetex njuthesis.dtx"
          post_compile: "mv njuthesis.pdf njuthesis-$VERSION.pdf" 
      
      - name: Zip Release Source
        run: |
          zip -r njuthesis-$VERSION.zip .vscode docs/njuthesis-sample.bib docs/njuthesis-sample.tex source/njuthesis.cls njuvisual.sty conf.txsprofile LICENSE README.md        
      
      - name: Zip CTAN Source
        run: |
          mkdir -p njuthesis/
          cp source/njuthesis-$VERSION.pdf njuthesis/njuthesis.pdf
          cp source/README-CTAN.md njuthesis/README.md
          cp source/njuthesis.dtx source/njuthesis.ins njuthesis/
          zip -r njuthesis-ctan-$VERSION.zip njuthesis/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            source/njuthesis-v*.pdf
            njuthesis-v*.zip
            njuthesis-ctan-v*.zip
