name: Build LaTeX document
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        latex: [xelatex, lualatex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis-sample.tex
          latexmk_use_${{ matrix.latex }}: true
          args: '-bibtex'
          # 与后面保持一致，因为大量的内容依赖于`njuthesis.pdf`这个名称
          post_compile: 'mv njuthesis-sample.pdf njuthesis.pdf'

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF_${{ matrix.latex }}
          path: njuthesis.pdf

  release:
    needs: build_latex
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Zip Release Source
        run: |
          zip -r njuthesis.zip . -x ".git/*" ".github/*" ".gitignore"
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: PDF_xelatex
          
      - name: Zip CTAN Source
        run: |
          mkdir -p njuthesis/doc/example
          cp -r chapters njuthesis.tex njuthesis.bib Makefile njuthesis/doc/example
          cp njuthesis.pdf njuthesis/doc
          cp README.md njuthesis/README_ZH_CN.md 
          cp README_EN.md njuthesis/README.md
          cp -r figure LICENSE njuthesis.dtx njuthesis
          zip -r njuthesis_ctan.zip njuthesis
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            njuthesis.pdf
            njuthesis.zip
            njuthesis_ctan.zip
