name: Release LaTeX document
on: 
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis.dtx
          args: '-bibtex'
        
      - name: Zip Release Source
        run: |
          zip -r njuthesis.zip . -x ".git/*" ".github/*" ".gitignore"
          
      - name: Zip CTAN Source
        run: |
          mkdir -p njuthesis/
          cp njuthesis.pdf njuthesis/njuthesis.pdf
          cp README.md njuthesis/README_ZH_CN.md 
          cp README_EN.md njuthesis/README.md
          cp -r figure/ LICENSE njuthesis.dtx njuthesis/
          zip -r njuthesis_ctan.zip njuthesis/
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            njuthesis.pdf
            njuthesis.zip
            njuthesis_ctan.zip
