---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        latex: [xelatex, lualatex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile to PDF
        uses: HermitSun/latex-action@v3
        with:
          root_file: njuthesis.tex
          latexmk_use_${{ matrix.latex }}: true
          args: '-bibtex'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
          njuthesis.pdf
